### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ZeusLT** [saleek-pa/Movie-API#1]
> Create a .env file in the root directory.
> 
>   REACT_APP_ACCESS_TOKEN_AUTH = your_tmdb_api_key
> Replace your_tmdb_api_key with the API key obtained from TMDB.

I was stuck on this part for a bit until I tried using "API Read Access Token" instead of "API Key". Please update the readme.

**Comment by saleek-pa** [comment]
Thanks for flagging this! 🚩 README has been updated to recommend using "Access Token Auth" over "API Key". Cheers for your valuable input! 🌟
