### ISSUE TITLE
Some shows don't show up in the watchlist

### ISSUE THREAD

**Issue by ZeusLT** [saleek-pa/Movie-API#3]
Some shows don't show up in the watchlist, for example "Stargate Universe"
![image](https://github.com/saleek-pa/Movie-API/assets/22300013/6a15057b-b034-47ec-b282-eb4ca0f6397b)
![image](https://github.com/saleek-pa/Movie-API/assets/22300013/276d5526-67bc-4308-8ac1-bdaeef50d171)
Here it is not in the list:
![image](https://github.com/saleek-pa/Movie-API/assets/22300013/ffffe371-221f-4015-9a7d-3b06fadade31)
And not in the completed:
![image](https://github.com/saleek-pa/Movie-API/assets/22300013/c425da3c-725e-4c7c-bc16-5d9867cf23dd)

**Comment by saleek-pa** [comment]
Thanks for pointing out the issue! 🚩 I've fixed the filtering error causing "Stargate Universe" and similar shows not to appear in the watchlist or completed list. Everything should be displaying correctly now. If you notice any other issues, feel free to let me know. Your input is greatly appreciated! 🌟
